# Pre-commit hooks for code quality
# Install with: pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # Black - Code formatter
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        language_version: python3.12
        args: ["--line-length=100"]
        exclude: ^(data_generation/|eda/)

  # Ruff - Fast Python linter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: ["--fix", "--line-length=100"]
        exclude: ^(data_generation/|eda/)

  # isort - Import sorting (handled by ruff, but kept for compatibility)
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length", "100"]
        exclude: ^(data_generation/|eda/)

  # mypy - Static type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
      - id: mypy
        language_version: python3.12
        args: ["--python-version=3.12", "--strict", "--ignore-missing-imports"]
        additional_dependencies:
          - types-requests
          - types-PyYAML
          - pydantic
        exclude: ^(data_generation/|eda/|tests/)
        files: ^(algorithms/|evaluation/|shared/).*\.py$

  # Check for merge conflicts
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
        args: ["--unsafe"]  # Allow custom tags
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-toml
      - id: debug-statements
      - id: detect-private-key
      - id: mixed-line-ending
        args: ["--fix=lf"]

  # Check for security issues
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-c", ".bandit", "-ll"]
        exclude: ^(tests/|data_generation/|eda/)

  # Validate pyproject.toml
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.15
    hooks:
      - id: validate-pyproject

# Global excludes
exclude: |
  (?x)^(
    \.git/|
    \.mypy_cache/|
    \.pytest_cache/|
    \.ruff_cache/|
    __pycache__/|
    \.venv/|
    venv/|
    build/|
    dist/|
    .*\.egg-info/|
    htmlcov/|
    \.coverage|
    data_generation/data/|
    __marimo__/
  )

# Set default language version
default_language_version:
  python: python3.12 