[project]
name = "guardrails-shared"
version = "1.0.0"
description = "Shared models and utilities for LLM Guardrails services"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.5.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build" 