generate *ARGS:
    uv run python main.py generate run {{ARGS}}

evaluate *ARGS:
    uv run python main.py evaluate run {{ARGS}}

sync:
    uv sync

format:
    uv run ruff format


up:
    docker compose up -d

down:
    docker compose down --volumes --remove-orphans

annotate *ARGS:
    uv run python main.py annotate {{ARGS}}