name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'data_generation/src/data_generation/**'
      - 'data_generation/tests/**'
      - 'data_generation/Justfile'
      - 'data_generation/pyproject.toml'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'data_generation/src/data_generation/**'
      - 'data_generation/tests/**'
      - 'data_generation/Justfile'
      - 'data_generation/pyproject.toml'
      - '.github/workflows/**'

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install Just
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to ~/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
      - name: Install dependencies
        run: just sync
        
      - name: Run formatter
        run: just format

  lint:
    name: Lint
    runs-on: ubuntu-latest
    continue-on-error: true  # Allow failures for linting
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install Just
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to ~/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
      - name: Install dependencies
        run: just sync
        
      - name: Run linter
        run: just lint

  test:
    name: Test
    needs: [format, lint]  # Run after format and lint, but don't fail if lint fails
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install Just
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to ~/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
      - name: Install dependencies
        run: just sync
        
      - name: Run tests
        run: just test 