name: EDA CI

on:
  push:
    branches: [ main, master ]
    paths:
      - 'eda/EDA.py'
      - 'eda/Justfile'
      - 'eda/pyproject.toml'
      - '.github/workflows/eda.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'eda/EDA.py'
      - 'eda/Justfile'
      - 'eda/pyproject.toml'
      - '.github/workflows/eda.yml'

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install uv
        uses: astral-sh/setup-uv@v5
          
      - name: Install Just
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to ~/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
      - name: Install dependencies
        run: just sync
        working-directory: eda
        
      - name: Run formatter
        run: just format
        working-directory: eda

  lint:
    name: Lint
    runs-on: ubuntu-latest
    continue-on-error: true  # Allow failures for linting
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install uv
        uses: astral-sh/setup-uv@v5
          
      - name: Install Just
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to ~/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
      - name: Install dependencies
        run: just sync
        working-directory: eda
        
      - name: Run linter
        run: just lint
        working-directory: eda
